-- ==============================================================================
-- SKEMA DATABASE E-SAPARI 2026 (UKMPR SAPARI)
-- Supabase Project: pmhsrkboqnxwcczaxajq
-- Salin seluruh kode ini ke Supabase Dashboard -> SQL Editor -> Klik "Run"
-- ==============================================================================

-- 1. TABEL TOKENS (Manajemen Token Sesi Seminar)
create table if not exists public.tokens (
    id uuid primary key default gen_random_uuid(),
    token text not null unique,
    title text default 'Token Sesi Seminar',
    duration_minutes integer not null default 60,
    expires_at timestamptz not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists idx_tokens_token on public.tokens(token);
create index if not exists idx_tokens_expires_at on public.tokens(expires_at);

-- 2. TABEL PARTICIPANTS (Database 148 Peserta Terdaftar)
create table if not exists public.participants (
    id bigint generated by default as identity primary key,
    norm_phone text not null unique,
    raw_phone text not null,
    name text not null,
    institution text,
    major text,
    proof_url text,
    created_at timestamptz not null default now()
);

create index if not exists idx_participants_norm_phone on public.participants(norm_phone);

-- 3. TABEL ACCESS_LOGS (Catatan Presensi & Upaya Akses Formulir Realtime)
create table if not exists public.access_logs (
    id bigint generated by default as identity primary key,
    token text not null,
    norm_phone text not null,
    participant_name text,
    status text not null, -- 'granted', 'token_expired', 'token_invalid', 'unregistered_phone'
    user_agent text,
    accessed_at timestamptz not null default now()
);

create index if not exists idx_access_logs_phone on public.access_logs(norm_phone);
create index if not exists idx_access_logs_token on public.access_logs(token);
create index if not exists idx_access_logs_accessed_at on public.access_logs(accessed_at desc);

-- ==============================================================================
-- KEBIJAKAN ROW LEVEL SECURITY (RLS)
-- Mengizinkan anon key untuk membaca, menulis, dan menghapus log/token
-- ==============================================================================

alter table public.tokens enable row level security;
alter table public.participants enable row level security;
alter table public.access_logs enable row level security;

-- Policies untuk tokens
drop policy if exists "Anon full access on tokens" on public.tokens;
create policy "Anon full access on tokens" on public.tokens
    for all to anon using (true) with check (true);

-- Policies untuk participants
drop policy if exists "Anon full access on participants" on public.participants;
create policy "Anon full access on participants" on public.participants
    for all to anon using (true) with check (true);

-- Policies untuk access_logs (bisa select, insert, delete untuk bersihkan log)
drop policy if exists "Anon full access on access_logs" on public.access_logs;
drop policy if exists "Anon insert and select access_logs" on public.access_logs;
create policy "Anon full access on access_logs" on public.access_logs
    for all to anon using (true) with check (true);

-- ==============================================================================
-- 4. INSERT DATA 148 PESERTA TERDAFTAR DARI CSV
-- ==============================================================================

insert into public.participants (norm_phone, raw_phone, name, institution, major, proof_url)
values
    ('087700109518', '087700109518', 'GALOH FRESTI SEFIRA', 'UHN IGBS DENPASAR', 'PENDIDIKAN AGAMA HINDU', 'https://drive.google.com/open?id=1J1tHgxQi20_f11lufq5nSh459L960jsb'),
    ('081913517444', '081913517444', 'I Made Agus Bayu Sedayatana', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Agama Hindu', 'https://drive.google.com/open?id=18XyvwwqpxOWLdShO2F32lcQ86IfWomGK'),
    ('082141969764', '082141969764', 'I DEWA AYU ANANDA', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=13BSij0iu2UjdHevzCbdDIJn3wKfQ4WfB'),
    ('087813262907', '‪0878‑1326‑2907‬', 'I PUTU DEVA PRAYOGA', 'Universitas Hindu negeri I Gusti bagus Sugriwa Denpasar', 'Pendidikan guru sekolah dasar', 'https://drive.google.com/open?id=1TvC9gnGCbsj7qN8Pbn1nknk0TAv3viYs'),
    ('082340898649', '082340898649', 'IDA AYU KOMANG TRI PUTRI PURNAMAYANI', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=1pHwlafN9i8ZuTcBC5o7-gD8Oda-tkAtO'),
    ('082317429693', '082317429693', 'Zalsabila', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Agama Hindu', 'https://drive.google.com/open?id=1kWwvzqsaOEqBWtLcE43Jv6VD9rebNiYW'),
    ('087728314032', '087728314032', 'Ni Made Septiantari', 'Universitas Hindu Negeri IGBS', 'PGSD', 'https://drive.google.com/open?id=1aLGwLEp-RrQ73xF7B9cRlaR2oLA_vU_F'),
    ('085738457233', '085738457233', 'KADEK EVI DARMAYANTI', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=1jsZlRYPTedaOBLIWb5OxrNJOqnqEHQz7'),
    ('081558144192', '081558144192', 'Ni Kadek Dwita Sari', 'UHN IGBS', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1Z3UPYSHOPEUnFFLb3ZSX3tUpVw5vLdP5'),
    ('087758238490', '087758238490', 'I PUTU AGUS YOGI PRATAMA', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=1ENP8RgO0R4Nzd0GhYFMIDjPMgr3lguc_'),
    ('087876974814', '087876974814', 'Ni Kadek Wulan Pratiwi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1twbr5FVtaqXlKMFVAdEFPqjv7D0z_PNw'),
    ('085737356505', '085737356505', 'Ida Ayu Putu Sri Wahyuni', 'universitas Hindu negeri I Gusti Bagus sugriwa Denpasar', 'PENDIDIKAN BAHASA INGGRIS', 'https://drive.google.com/open?id=1J87kMLWKdG2DI5EHzPzUKHF1QCBtxbNw'),
    ('082145042860', '082145042860', 'Ni Kadek Septiana Sari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=14N97QCp714p9W897uxnc9sXB3TEIswQs'),
    ('085738369967', '085738369967', 'Komang Gede Putra Handika', 'Universitas Hindu I Gusti Bagus Sugriwa Denpasar', 'Ilmu komunikasi hindu', 'https://drive.google.com/open?id=1mb04TCktTaiB1_1qzXiYp01ornfMm95q'),
    ('085607679583', '085607679583', 'Ni Wayan Wahyuni Widiastuti', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Sastra Agama Dan Pendidikan Bahasa Bali', 'https://drive.google.com/open?id=1UWM-LeR2VBB20p3hNmiM0m03FIP8NEnc'),
    ('085524738888', '085524738888', 'Iluh gede lestari', 'UHNl I GUSTI BAGUS SUGRIWA Denpasar', 'S1 Pendidikan agama Hindu', 'https://drive.google.com/open?id=1YWROyXXORgxG-wHmUtypdaOyACh3BR1O'),
    ('081335650825', '081335650825', 'YOSUA GABRIEL TAMPUBOLON', 'UNIVERSITAS JAMBI', 'MANAJEMEN PEMERINTAHAN', 'https://drive.google.com/open?id=19Okhk4eBUPuX9N7gf3Q03gLgw_jOzRm3'),
    ('085792311292', '085792311292', 'Komang Tri Saskarani', 'UHN IGBS Denpasar', 'Pendidikan Agama', 'https://drive.google.com/open?id=1pwk666kAM0m3oG8zwsY52qFGjwydxSlv'),
    ('085939536921', '085939536921', 'Luh Febi Ernasari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Agama Hindu', 'https://drive.google.com/open?id=18IURBNdoFCkw1TuIPUFhEUFUUW6UAF4T'),
    ('085964354088', '085964354088', 'Ni Wayan Kania Putri', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Agama', 'https://drive.google.com/open?id=189SBPQrliJLm2e_RHxA1AlXpoRSE73uB'),
    ('087841159955', '087841159955', 'Ni Made Dwi Novita Sari', 'UHN I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1eqhup3ASQ-Fbp9RzCzZ2AyrOewkRB243'),
    ('081246425858', '081246425858', 'Ni Komang Sri Rahayu', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=1JDC1Scvz5z6exxeW-PqLdwsw5ror-Dyb'),
    ('081239093215', '+62 812-3909-3215', 'Made Ayu Kusuma Dewi', 'UHN', 'PGSD', 'https://drive.google.com/open?id=1djlDi4SJR28d6V-iSDI5oALMSshrG1nn'),
    ('087843580687', '‪+62 878‑4358‑0687‬', 'NI WAYAN DIVYA SUTRISNA DEWI', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'S1 PGSD', 'https://drive.google.com/open?id=18uM8i49nCDvldcfytGouMU5PBF-5tWKi'),
    ('081237926941', '081237926941', 'NI LUH PUTU MAYRA SOMAWATI', 'UNIVERSITAS HINDU NEGRI I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=19G8VyUhen0I8fbF2t5mSGPilA_IdBR4f'),
    ('08213813465', '08213813465', 'Dwi Yanti Prameswari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1Nw_PhP2oC4xKRjKBPF2WEkzRiPXxaVg-'),
    ('082237670543', '082237670543', 'Ni Wayan Eka Pradnyani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1D0iOjCHdelSATIL8pLK-FK64Xhrpd6Nw'),
    ('087778981543', '087778981543', 'I Gusti Putu Ngurah Eka', 'Fakultas Dharma Acarya', 'PGSD', 'https://drive.google.com/open?id=1C6pziv4E1sVEYiEQChYJfOOT5wi_U5_5'),
    ('085936661648', '085936661648', 'I KOMANG MULIARTANA', 'Uhn Sugriwa Denpasar', 'Pgsd', 'https://drive.google.com/open?id=10ZNf670V2zXMbscLLSNeMg8z8mQ4wLa8'),
    ('085126944313', '085126944313', 'Ni Made Jelita Asri Nariswari', 'UNIV UHN SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=1Rul58qCEShc0Ih4EjBmw00j3k1xTPpU8'),
    ('0816950624', '0816950624', 'Ni Luh Dian Ayu Antari', 'UHN SUGRIWA', 'PGSD', 'https://drive.google.com/open?id=1epjW4tk3UPC26O4gdOiIFJIdbuwT_6j3'),
    ('087751022952', '087751022952', 'Ni Putu Ayu Nilayanti', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'Pendidikan bahasa inggris', 'https://drive.google.com/open?id=1R1JX8Cn1nS4j9ADRCMITDwn6MyURkwz0'),
    ('083145686703', '083145686703', 'Putu eni', 'Universitas i gusti bagus sugriwa', 'Pendidikan guru sekolah dasar', 'https://drive.google.com/open?id=1AziQlSqPrcTsJcjsZAsABq_U1HrVPhcZ'),
    ('085964281021', '085964281021', 'Ni Putu Winda Yuliantari', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=1ZsNanvaFuN2bdLECSgSwi5lk4Epko25z'),
    ('085737149291', '085737149291', 'Ni Made Swartini', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1kukTCaNwqhftDCQvwSEO34QXVqAKpcYO'),
    ('087866168412', '087866168412', 'Id2a Ayu Candra Trisna Radnyani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1nmqWDb2slK9KXEOsrruqEP2Huclji65R'),
    ('081907716149', '081907716149', 'Ni Wayan Karsika Yani', 'UHN IGBS DENPASAR', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=1tSal5D9_c9qUnGMQbGKMeuzHWz6L2lyt'),
    ('087866775734', '087866775734', 'Ni Komang Sulistiani', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=122Fud5LElDwja_ocqQ0kNMmxwlGl2K6U'),
    ('083114622178', '083114622178', 'Cok. Istri Sri Wulandari', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=1c39b9Q7KwFK4-lQCZWDQtsR-ZragnPdo'),
    ('085853003016', '085853003016', 'Ni Kadek Sukma Diana', 'UHN Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1P-mgAN5XgkhF8c5HJdXfSYmg5r-MVP2n'),
    ('081542371366', '081542371366', 'Luh Ade Trisnawati', 'UHN I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1-WV9xAczTaxbftCH6HQSScx-7Fg6sdHK'),
    ('081218824127', '081218824127', 'Ni Putu Ayu Manis Adnyani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=152Y5YcON1mKkOILu0Ydp6wDS3Y9mlUQQ'),
    ('081354034621', '81354034621', 'Siti Nur Hasanah', 'Universitas Musamus', 'Law', 'https://drive.google.com/open?id=1cVkCHTlGNSCLwTApPh7LnVSmg9U6LnE6'),
    ('085756319637', '085756319637', 'DEWA AYU RATNA DEWI', 'UHN I Gusti Bagus Sugriwa (Kampus Bangli)', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1RPmpoz0zBtNvNVYSTFNisvijl8JffJPM'),
    ('087753480288', '087753480288', 'Ni Ketut Sehena', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1AduSfVSXHYSAiwMDzoc6OzQV1HjsdZp4'),
    ('081353423603', '081353423603', 'I Putu Artha Mahardika', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa', 'Pendidikan Agama', 'https://drive.google.com/open?id=1OKvIo1plsnSR_ba8tzjsMbMVZr-Xjc1X'),
    ('081529216330', '081529216330', 'Anindita Bunga Aulia Pande', 'UHN I Gusti Bagus Sugriwa Denpasar', 'S1 Pendidikan Agama Hindu', 'https://drive.google.com/open?id=12fF0qZmNjJSUGVfFni1_Ifqc_O7XA6Vv'),
    ('081809194002', '081809194002', 'Dewa Ayu Mirah Utami', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1sbJ3gIAs2jTIZazrdwtzhSOIB_-mWg7k'),
    ('0881037780811', '‪0881037780811‬', 'Intan Kartika Oktavia Pratiwi', 'Universitas Hindu I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar (PGSD)', 'https://drive.google.com/open?id=1Kp5aXIqsHGMf8MI9v3C-UFrL361WojR4'),
    ('085942524332', '085942524332', 'Ni Putu Nisa Oktarini', 'UHN IGBS DENPASAR', 'Pendidikan bahasa Inggris', 'https://drive.google.com/open?id=1PBlEbuIBXvC2njwZ3DVk-NktWmNII181'),
    ('085792351698', '085792351698', 'Ni Kadek PujaYanti', 'UHN I Gusti Bagus Sugriwa Denpasar', 'S1 Pendidikan Guru Sekolah dasar', 'https://drive.google.com/open?id=1hdSPCHeg0w2i41iMK322DT0Npy5WB_Z4'),
    ('085737217625', '085737217625', 'I KADEK ANGGA', 'UHN SUGRIWA', 'PGSD', 'https://drive.google.com/open?id=19wCspNkU_90gLhqFEEPXdtVI9sCQQESg'),
    ('087866119113', '087866119113', 'Ni Kadek Dwik Novi Yanti', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pgsd', 'https://drive.google.com/open?id=1aNbeZjCT7IL0Bbjqn0qBsJ5mmnmZ9Y7c'),
    ('085179993281', '085179993281', 'Desi Rahmandani', 'Universitas Nasional', 'Manajemen', 'https://drive.google.com/open?id=1A6jPQN42o5j0DE-v1Jq5rUWp4H3AWth_'),
    ('08993314585', '08993314585', 'Ni Kadek Erlina', 'UHN IGB Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1Wm3OUmQ_q246rrpyU3WjV5da5-wSxnzk'),
    ('087750632296', '087750632296', 'Ni Kadek Hadi Yani', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1Hgbs8IN18PwgrexTKyukAnAMTx4oTkav'),
    ('081809964050', '081809964050', 'Komang Ayu Astrini Mahadevi', 'UHN I Gusti Bagus Sugriwa', 'Pendidikan guru sekolah dasar', 'https://drive.google.com/open?id=1y773t78jFYhOmj0hEup7nNeuCrbyTj2W'),
    ('089510312989', '089510312989', 'Ni Putu Ayu Dian Pradnyawati', 'UHN I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=119RI6ElCiJQa-OW2t2HFM2yk6vUbpuaS'),
    ('087762639041', '087762639041', 'Ni Luh Ariyanti', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan bahasa Inggris', 'https://drive.google.com/open?id=1rpzfAePEnS73L6fYjqnJ0rudr8vr5G52'),
    ('087763377840', '087763377840', 'Ni Ketut Ory Naira Pratiwi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1sr0uWSdAm5Wr7DD9r7yYRypSbq0P3G-f'),
    ('081936612924', '081936612924', 'Ni Komang Ary Sastri Ani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1S9EeyGpF-PAyp-yGte0uN_6ngpTlbxKD'),
    ('087743434255', '087743434255', 'Ni Putu Eka Novi Yani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1h_DGs9WioArZwb7E3vDdjbpO4RIjvOiN'),
    ('081339890763', '081339890763', 'Ni Made Ayu Kumalasari', 'Universitas Hindu Negeri I Gusti Bagus sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1LLf37x4vfihcCJUeA27z4xzl5LcCzWQ0'),
    ('081558772787', '081558772787', 'Ni Kadek Ida Febriyanti', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1rruRI-VjhrgLRatTps6pLbiELJtXPcvM'),
    ('085656950545', '085656950545', 'I Gusti Ayu Widya Saraswati', 'UHN IGBS', 'Pendidikan Agama Hindu', 'https://drive.google.com/open?id=1MT07DBJWrqeFxTAxd4fAnWWpVK8Ou1e0'),
    ('085935066270', '0859-3506-6270', 'I PUTU PRABAWA KUSUMA WISESA', 'Hmj Teologi Hindu', 'Teologi Hindu', 'https://drive.google.com/open?id=1Sgxmt7eiT-PQ_gmf5ody5MssIv_rxwH3'),
    ('085935066270', '0859-3506-6270', 'I PUTU PRABAWA KUSUMA WISESA', 'Hmj Teologi Hindu', 'Teologi Hindu', 'https://drive.google.com/open?id=1PNlUsRe8j0zxTngs4aJlqcoCeZsrBZhE'),
    ('081935187207', '081935187207', 'I made radesya satria pramana', 'Hmj teologi hindu', 'Teologi hindu', 'https://drive.google.com/open?id=1d5EAiFXnm9Naa1L_yOKE9lmUvGSFqM9I'),
    ('081935187207', '081935187207', 'I made radesya satria pramana', 'Hmj teologi hindu', 'Teologi hindu', 'https://drive.google.com/open?id=1g6EwiQVhtIfyZ7Ddp8irf-f9wm6gZ5N0'),
    ('085643024595', '085643024595', 'Ni Putu Dian Apriliani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1TyVjmqhk-Vef9UDjtXIl6QjdQsVsDNvs'),
    ('082147353208', '082147353208', 'Ni Luh Putu Intan Astari Putri', 'UHN SUGRIWA', 'PGSD', 'https://drive.google.com/open?id=1W3DEj_VMRQDFdsgfTgTNPa7d0SOImh1E'),
    ('0881038941006', '0881038941006', 'I Gusti Bagus Damar Dinata', 'UHN IGBS', 'PGSD', 'https://drive.google.com/open?id=1VNs5u6tzWPFwIuT0gS88klCWAtEcw98k'),
    ('083103016053', '083103016053', 'Hotma Roulina Silaban', 'Universitas Udayana', 'Fisika', 'https://drive.google.com/open?id=1DACJDcdVL-_lwin-9FxfYZJzBRmLTYSD'),
    ('083150877440', '083150877440', 'Ni Luh Wahyu Erniasih', 'UHN Sugriwa Denpasar', 'Pendidikan bahasa Inggris', 'https://drive.google.com/open?id=1yC8N6DjGFOnvLb6q6MXSraXST9pZEqDy'),
    ('087798451242', '087798451242', 'I Gusti Ngurah Dwi Andika', 'UHN IGBS', 'PGSD', 'https://drive.google.com/open?id=1S0iQEIUQ9bR0KVsBNvuqNHYeKKrqKEak'),
    ('081346459130', '081346459130', 'SARI DEVI ARDIYANTI', 'universitas Musamus', 'hukum', 'https://drive.google.com/open?id=1211I07p0Ccqir3KWAvFaB85yHUVSCvDH'),
    ('085737866325', '085737866325', 'Ni Luh Anggreni', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1KOu-lTUuUBJ7-u3Y5byLnjMbC1ZeEtvD'),
    ('0895413446767', '0895413446767', 'Gede Adi Pramana', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Informatika', 'https://drive.google.com/open?id=1TVkTbAb0G8HAyTF2NOEBoakA_8R0Crfe'),
    ('085739651927', '+62 857-3965-1927', 'I Gusti Bagus Yuda Putra', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=18ge9QyOUTG3iXXHpgh2dDezOsmg-XJCU'),
    ('085815256961', '085815256961', 'ni luh putu erika aureli kirana putri', 'uhn sugriwa denpasar', 'pendidikan bahasa inggris', 'https://drive.google.com/open?id=1lnXgNa8ZZ-myMYFFxsy_G6-ShjgUh-04'),
    ('085738924125', '+62 857-3892-4125', 'Komang Kusumaningsih', 'Mahasiswa', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1ZVm2cibvkvYp5zcm6quCITf1orB6sUN1'),
    ('087858765709', '087858765709', 'Ni Kadek Intan Kusumadewi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1dPS06Zsjmoul8VljvkGMOyGE-itxLlCK'),
    ('081338098445', '081338098445', 'Dewa Ayu Jasmine Yuli Allora', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1gOUjQKmkJ_z5jJ1Xu_Bt53lhDxJJlmFE'),
    ('085607194451', '085607194451', 'Ni Made Suartini', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1arIL1QHUCOJzmJusFndcmUC6MyvuA9tI'),
    ('087701169434', '087701169434', 'I Made Tangkas Murdana Putra', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1ffk7osGVcAhYA0VLJb18RLRLoK48keBP'),
    ('082247255916', '082247255916', 'I Gede Tangkas Mariatna', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=1DGMQQd4G2dqQfWlGdNOiJxBhqvhQhC2-'),
    ('082290255451', '082290255451', 'Nengah Selvi Oktavia', 'UHN IGBS Denpasar', 'PGSD', 'https://drive.google.com/open?id=1vmagRCJdA3t1c7cqQ0YbSLBcClKEO7C3'),
    ('083115315083', '083115315083', 'Desak Gede Laksmi Dewi Kesawa', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'S1 Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1wd-dXk-a7oseiOfV1ibsRbbI1duXq-QF'),
    ('085737852956', '085737852956', 'Luh Gede Vallentchya Kryana Putra', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1ryyMXyszQ_b1inautdyKn_bBB2G6C1U4'),
    ('083114188076', '083114188076', 'Ni KD. Maela Utami Praja Dalem', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1Yb5761dYK-PUKd4OFCyiaw70yO9Ybbnt'),
    ('085721764512', '085721764512', 'Ni Wayan Sugiantini', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Agama Hindu', 'https://drive.google.com/open?id=1L_wdaeK3srdpe2maBtcWLY-DlgJPaO-8'),
    ('081238969927', '081238969927', 'NI NENGAH SUTRA DEWI', 'UHN I GUSTI BAGUS SUGRIWA DENPASAE', 'PGSD', 'https://drive.google.com/open?id=1mvLkWE9xM_oeHr2JeHOQ6bqs30PDS5er'),
    ('087735508358', '087735508358', 'Ni Kadek Ayu Sri Wahyuni', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa', 'PGSD', 'https://drive.google.com/open?id=1xTZdS9kn9Zow6TkatodAxXn4ndBYHQGd'),
    ('083119303579', '083119303579', 'Desak Made Citra Rejeki', 'UHN', 'PGSD', 'https://drive.google.com/open?id=1pzrUuau1DLmyA0To8eBbemAKMqVg14dG'),
    ('087785209039', '87785209039', 'I Gusti Ayu Mirah Ratna Dewi', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=1nxu4dMC91oB6Qnqi-PiW_SDG7VfXh2_u'),
    ('0881037355394', '0881037355394', 'Dewa Ayu Gede Riandini Adnyaswari Merta', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1XlDOeF8EeGzJGP_JfyJofEJ2-5lUqTQJ'),
    ('087841901344', '087841901344', 'Ni Kadek Adelia Meliana', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1GD-tpb9b8vVOYYPtyqZQX-iM8Ccifvne'),
    ('081236737023', '081236737023', 'Nyoman Ayu Sastrayoni', 'Uhn sugriwa denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1jLR42JUX12da0lvcxdx9Bxhcff4ARtYh'),
    ('081529836074', '081529836074', 'I Dewa Ayu Nyoman Widiastri', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1KUlrYHh6_Os1vYCMjGVcNuvXkKWxvEX0'),
    ('081353067564', '081353067564', 'Pande Ketut Aswinda Saucarani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'S1 Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1qHY0_jjA0KLy7mvtrE7p4z54RCtxJFaW'),
    ('08191602046', '08191602046', 'Desak Gede Bintang Prami Gita', 'UHN', 'PGSD', 'https://drive.google.com/open?id=1FujlNjXgMRAZbRG0uRFfPgIItESGmE-m'),
    ('085738184441', '85738184441', 'Ni Kadek Sastya Acnis Dewanti', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'S-1 Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1gQqB7Bef6kMmgYfcXAghHz3irm0fksBH'),
    ('0895412391919', '0895412391919', 'PUTU MEISYA DEWANTARI', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=1N1FhSFWw-MEZJkjrrT1KCw284Rh-QXZc'),
    ('08223666092', '08223666092', 'I Gusti Ayu Mirah Pratiwi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1O4H85-w7u9TE0IPvDX2x63rvQxrhJPXA'),
    ('085847835044', '085847835044', 'Ni Nengah Dian Pradnya Sari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1tjhvPvJgBoRmb5hl42MNx2Z2n_9fT8-a'),
    ('085941397276', '085941397276', 'Ni Komang Anggun Kristiani', 'UHN I Gusti Bagus Sugriwa Denpasar', 'PBI', 'https://drive.google.com/open?id=1JQawAMy9Ivu0Oz3zTDfo_Bs-SdIOAVh8'),
    ('087702887953', '087702887953', 'Ni Putu Sonia Sri Saraswati', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa, Fakultas Dharma Acarya', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1Sru6zWZG9KjVaY5TywT7Lz8Uc9WjPhqh'),
    ('085737885331', '085737885331', 'Ni Kadek Yuniari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1el3hvxwI1Ksyg9-RkJqD-EGVlPO1g2E-'),
    ('085739587024', '85739587024', 'Ni Made Widyanitasari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1kKO1rr_VehmPJ9vbbtchjEtPlYtYBXdw'),
    ('083845087919', '083845087919', 'Ni Putu Ari Sintya', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1dLmUn99qlkjJfOgIWL4AWnZ0bZERiJxC'),
    ('085179993281', '085179993281', 'Desi Rahmandani', 'Universitas Nasional', 'Manajemen', 'https://drive.google.com/open?id=1ZT5fMxjUahdKCJIwpXomKZPnvlkLnQjV'),
    ('0881037563776', '0881037563776', 'Ni Luh Gede Cyntia Suari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1wD6pO_HbIrNGb1NvegUuQ61kA5Kjrj7p'),
    ('0881038885155', '0881038885155', 'Anak Agung Yulia Cempaka Putri', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1pPh9ws6r5VPmCGQ9A-vmsJs1Uy5l8LN0'),
    ('085829222872', '085829222872', 'Pande Nyoman Tara Waradhya', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1ZN4R66A5q-VQdU24VVxyNjiaQ3Pz37Uu'),
    ('085737064058', '085737064058', 'Ni Putu Eka Darma Yanti', 'universitas hindu negeri i gusti bagus sugriwa denpasar', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=1H3C3r-IC0YewlFT6cDWNQgt_y_6kHktm'),
    ('085737064058', '085737064058', 'Ni Putu Eka Darma Yanti', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=18kTDhQk6zuN6G_IeZ-E750SseHhBfIq9'),
    ('081236591238', '081236591238', 'Ni Komang Enix Vitariani', 'UHN', 'PGSD', 'https://drive.google.com/open?id=1BzrNM5J2EA_NLKA416Llh0UtzaubdlEG'),
    ('08873731834', '08873731834', 'Ni Kadek Ayu Puja Aryanti', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1DRBliYoLDkIRs9MRwXZEduxC06prpEUK'),
    ('085934604971', '085934604971', 'Ni Luh Gede Linda Pradnyaswari', 'Universitas Udayana', 'Pengelolaan Perhotelan', 'https://drive.google.com/open?id=1Y-GkpZl8yYfGkryyTd_Ly9_CZEvU_ydW'),
    ('083114878395', '083114878395', 'Ni Nengah Widiasih', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=17Gv6F5yOy52-NVzbC-2pU-53wVIYvY-R'),
    ('085352653203', '085352653203', 'KOMANG DESI', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PENDIDIKAN AGAMA', 'https://drive.google.com/open?id=1BMaXhJ1RN4uZGa-wJzidVxpjUu4ZFvzp'),
    ('082339530776', '082339530776', 'Ni Kadek Sri Juliantari', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1X3FMpCqTo8O9LFkzvkB7CNsfVwYhDtLf'),
    ('083856214834', '083 856 214 834', 'Ni Nengah Dian Pratiwi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1aIDAI-Dj43ao_xPVVuqFS4hHrb1FZYvf'),
    ('081938811581', '081938811581', 'Ni Komang Dina Lestari', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1Am0W3mTQmZPoeZ3UnmDnlBMZn1g7Gq0E'),
    ('085338015238', '085338015238', 'Muhammad Fadhil', 'Universitas Udayana', 'Sastra Jawa kuno', 'https://drive.google.com/open?id=1Ig7SbYUTW3i6s9u5kvHHeBW4ssZfQYiM'),
    ('085738360434', '085738360434', 'Ni Pande Putu Dhyani', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar (UHN)', 'Pendidikan Guru Sekolah Dasar (PGSD)', 'https://drive.google.com/open?id=1xx-BkHKWRDs5LikabDSvDtGCx1sAT7I-'),
    ('087780350136', '087780350136', 'Ni Nengah Arisanti', 'UHN IGBS DENPASAR', 'PENDIDIKAN GURU SEKOLAH DASAR', 'https://drive.google.com/open?id=1nofdS1_MPAOpSHBRozwlOz9BU-0srygU'),
    ('083130766248', '+6283130766248', 'Putu Sari Kusuma Devi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1aDNPphFxQvaiJQKd7nLogXlrTPIAHtXP'),
    ('085386633909', '085386633909', 'Ni Putu Ellysia Berliana Nandini', 'Uhn I Gusti Bagus Sugriwa Denpasar', 'PGSD', 'https://drive.google.com/open?id=1jJxPeRXf_ILIkOsnRStev7vMRm7bgtKk'),
    ('081529945853', '081529945853', 'Ni Made Ayu Rai Juniari', 'UHN Sugriwa Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1wtJq7efb9H1HlXKp4Ub_hAxEsrRGY7f6'),
    ('083111691588', '083111691588', 'Ni Kadek Ayu Nilawarsiki', 'Universitas Hindu Negeri IGBS Denpasar', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1LKJ0BMC4Xl6BqomvL1zDilBIj7LKiP3N'),
    ('081260025417', '0812 6002 5417', 'Stefani Madame Sinaga', 'Universitas Udayana', 'Fisika', 'https://drive.google.com/open?id=1DarXNUPzhvVygolxC2wxHe6g5GT_9ju9'),
    ('08135391430', '+62 813-5391-430', 'Ade Aying Megantari Pulasari', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'S1 Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1I8Wd7t80Kdm93zZBU7b2lRWUtndNvcU2'),
    ('081803312866', '081803312866', 'Ida Ayu Putu Sri Wahyu Cahyani Dewi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1mRFdWvyPouKqL__y_vd1PL96ScIq6pUF'),
    ('081977393111', '081977393111', 'Luh Gede Intan Pratiwi', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Ilmu Komunikasi', 'https://drive.google.com/open?id=1kwrJQjHOZKPovur4LooDXsEUqmZfbvK-'),
    ('087859631128', '087859631128', 'Dewa Ayu Tiara Jayanti', 'UHN IGBS DENPASAR', 'SAPBB', 'https://drive.google.com/open?id=1WDb5uSncR-yIBivN635tKVXPf7e0aOe9'),
    ('087855606885', '087855606885', 'I Gede Budhi Suartama', '-', 'Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1Dn8-18lUjmRyG2vBoySBF8uhw8XJX-Fy'),
    ('085704185117', '085704185117', 'NI WAYAN SUKARINI', 'UNIVERSITAS HINDU NEGERI I GUSTI BAGUS SUGRIWA DENPASAR', 'S2-ILMU KOMUNIKASI HINDU', 'https://drive.google.com/open?id=1vBW0-86ABxBzzdckuHReZhfNRGOgkXY0'),
    ('0895413314877', '0895413314877', 'Made Dwi Arisintya Ardianti', 'Universitas Warmadewa', 'Kedokteran', 'https://drive.google.com/open?id=1sXPK5bc_mvYtPGHgZ1xbhALpWbQc5E3s'),
    ('081337843441', '081337843441', 'Pande Komang Ayu Sasih Purnama Sari', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'Pendidikan Agama', 'https://drive.google.com/open?id=1ABU65qTyEqdBWYmkSZGOts1lUjY-Bmqr'),
    ('081262759394', '+62 812-6275-9394', 'I Made Destananda Cahya Pramana', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=18l9O9_R9Yv4il31HF3O3pVhlT9hjNY4A'),
    ('081907436606', '081907436606', 'Ni Putu Nadia Kirani', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'PGSD', 'https://drive.google.com/open?id=1dKRigi2L21tJlnDcTS5eq7N5igpFTcj6'),
    ('087702761399', '087702761399', 'Ni Luh Putu Kesya Martiani', 'UHN I Gusti Bagus Sugriwa Denpasar', 'Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1jDdWskP0HfcB9-UYvu9jAe9HmHvyVjYN'),
    ('087833650874', '‪087833650874‬', 'IGusti Ayu Agung IsmaDewi', 'uhn IGusti Bagus Sugriwa Denpasar', 'S1 Pendidikan Guru Sekolah Dasar', 'https://drive.google.com/open?id=1fd5VfKKYss29tR2lpqiAeGrJivkHdzqY'),
    ('0881038162155', '0881038162155', 'I Putu Restu Adi Nugraha', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'Sastra Agama dan Pendidikan Bahasa Bali', 'https://drive.google.com/open?id=1uop3E4qhrQm1kQLPs8V8jiBnt_49JIdH'),
    ('081238567967', '081238567967', 'I Wayan Parwita', 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'S1 Sastra Agama dan Pendidikan Bahasa Bali', 'https://drive.google.com/open?id=1dXEDNF2f2GGbqfdwG5KcL1N7q3xouWSr'),
    ('082314715319', '082314715319', 'Ni Wayan Wahyuni', 'UHN I GUSTI BAGUS SUGRIWA DENPASAR', 'S1 Pendidikan Bahasa Inggris', 'https://drive.google.com/open?id=1K8OTx04Lxihek4hJrTu3f_klY6OT60Fh'),
    ('0895373990099', '0895373990099', 'Ida Ayu Windya Utami Puteri', 'Uhn I Gusti Bagus Sugriwa Denpasar', 'Fakultas Dharma Acarya prodi pendidikan bahasa Inggris', 'https://drive.google.com/open?id=1e_Sk10quvDcYAhOXD8sy3058nUCAt39H')
on conflict (norm_phone) do update set
    name = excluded.name,
    raw_phone = excluded.raw_phone,
    institution = excluded.institution,
    major = excluded.major,
    proof_url = excluded.proof_url;
